services:
  - type: web
    name: app-colores
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: app-colores-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: u9733091150@gmail.com
      - key: MAIL_PASSWORD
        value: lbnm kils jczn egsl
      - key: MAIL_DEFAULT_SENDER
        value: u9733091150@gmail.com
      - key: STRIPE_SECRET_KEY
        value: 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
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_live_51S4nGNCCYxyEFt2N5PYWsKct974FyQKO7CMBThlBPGhA8SuYdk7Ue5hX6aHEI0QNA9QLrjR9r4rb5GeLegxeh4u800ELqvIBUP
      - key: STRIPE_PRODUCT_ID
        value: prod_T0p3Og8mjYPd9t
      - key: STRIPE_PRICE_ID
        value: price_1S4nPHCCYxyEFt2NixnnwZoD
      - key: STRIPE_WEBHOOK_SECRET
        value: ""

databases:
  - name: app-colores-db
    plan: free
    databaseName: app_colores
    user: app_colores_user
